># 11주차 숙제
### 최승호 24 석사 / 학번: 2024158814
- ["Reshaping and flattening multidimensional arrays" 까지 코딩하고 실행](https://numpy.org/doc/stable/user/absolute_beginners.html#)

Welcome to NumPy!

Installing NumPy

In [133]:
#pip install numpy

How to import NumPy

In [9]:
import numpy as np

Reading the example code

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

What’s the difference between a Python list and a NumPy array?

What is an array?

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
print(a[0])

[1 2 3 4]


More information about arrays

How to create a basic array

In [10]:
a = np.array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [15]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

Adding, removing, and sorting elements

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [20]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [22]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How do you know the shape and size of an array?

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [24]:
array_example.ndim

3

In [25]:
array_example.size

24

In [26]:
array_example.shape

(3, 2, 4)

Can you reshape an array?

In [27]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [32]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [33]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indexing and slicing

In [38]:
data = np.array([1, 2, 3])

data[1]

2

In [39]:
data[0:2]

array([1, 2])

In [40]:
data[1:]

array([2, 3])

In [41]:

data[-2:]

array([2, 3])

In [42]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [43]:
print(a[a < 5])

[1 2 3 4]


In [44]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [45]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [46]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [47]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [49]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [50]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [51]:
print(a[b])

[1 2 3 4]


In [52]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


How to create an array from existing data

In [53]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [55]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [56]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [57]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [58]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [60]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [61]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [63]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [64]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
b2 = a.copy()

Basic array operations

In [66]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [67]:
data - ones

array([0, 1])

In [68]:
data * data

array([1, 4])

In [69]:
data / data

array([1., 1.])

In [70]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [71]:
b = np.array([[1, 1], [2, 2]])

In [72]:
b.sum(axis=0)

array([3, 3])

In [73]:
b.sum(axis=1)

array([2, 4])

Broadcasting

In [74]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

More useful array operations

In [75]:
data.max()

2.0

In [76]:
data.min()

1.0

In [77]:
data.sum()

3.0

In [78]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [79]:
a.sum()

4.8595784

In [80]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [81]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
data[0, 1]

2

In [83]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [84]:
data[0:2, 0]

array([1, 3])

In [86]:
data.max()

6

In [87]:
data.min()

1

In [88]:
data.sum()

21

In [89]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [90]:
data.max(axis=0)

array([5, 6])

In [91]:
data.max(axis=1)

array([2, 5, 6])

In [92]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

Creating matrices

In [93]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [94]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [95]:
np.ones(3)

array([1., 1., 1.])

In [96]:
np.zeros(3)

array([0., 0., 0.])

In [97]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.58687   , 0.00494681, 0.86942315])

In [98]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [99]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [100]:
rng.random((3, 2)) 

array([[0.37899319, 0.21377943],
       [0.02327735, 0.20574607],
       [0.18987187, 0.3078114 ]])

Generating random numbers

In [101]:
rng.integers(5, size=(2, 4)) 

array([[3, 4, 4, 4],
       [4, 1, 1, 0]], dtype=int64)

How to get unique items and counts

In [102]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [103]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [104]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [105]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [106]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [107]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [108]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [109]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
print(indices)

[0 1 2]


In [111]:
print(occurrence_count)

[2 1 1]


Transposing and reshaping a matrix

In [112]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [114]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [116]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

How to reverse an array

In [118]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
reversed_arr = np.flip(arr)

In [120]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [121]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [122]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [123]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [124]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [125]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [126]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [127]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [128]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [129]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [131]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
